# Generated by Django 5.2.7 on 2025-12-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('CAFE', 'Cafés Especiales'), ('SNACK', 'Pasteles & Snacks')], db_index=True, default='CAFE', max_length=10),
        ),
    ]
